### ISSUE TITLE
Homebridge tado ac - SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by iHakia** [nitaybz/homebridge-tado-ac-old#13]
Hello 
I'm trying to install the tado ac homebridge 
This is my first time using homebridge. so please understand the noob question

I'm getting the following error 
 Loaded plugin: homebridge-tado-ac
[7/14/2017, 4:44:43 PM] Registering accessory 'homebridge-tado-ac.TADO'
[7/14/2017, 4:44:43 PM] ---
[7/14/2017, 4:44:43 PM] There was a problem reading your config.json file.
[7/14/2017, 4:44:43 PM] Please try pasting your config.json file here to validate it: http://jsonlint.com
[7/14/2017, 4:44:43 PM]
/opt/node/lib/node_modules/homebridge/lib/server.js:197
    throw err;
    ^

SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at Server._loadConfig (/opt/node/lib/node_modules/homebridge/lib/server.js:191:19)
    at new Server (/opt/node/lib/node_modules/homebridge/lib/server.js:52:38)
    at module.exports (/opt/node/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/opt/node/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

This is my Json file - passed ok thru jsonlint

{
  "bridge": {
    "name": "Homebridge",
    "username": "bridge",
    "port": 51826,
    "pin": "031-45-154"
  },

 "accessories": [
{
  "accessory": "TADO",
  "name": "Tado",
  "homeID": 18916,
  "maxValue": 31,
  "minValue": 16,
  "zone": 1,
  "username": "email@bla.com",
  "password": "pass",
  "useFanSpeed": "AUTO",
  "useSwing": false,
  "tadoMode": "MANUAL",
  "useFahrenheit": false
}
]
}

Any help will be appreciated :)

**Comment by nitaybz** [comment]
seems like your config is valid... try this:

```
{
	"bridge": {
		"name": "Homebridge",
		"username": "CA:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},

	"description": "This is an example configuration file",

	"platforms": [],

	"accessories": [{
		"accessory": "TADO",
		"name": "Tado",
		"homeID": 18916,
		"maxValue": 31,
		"minValue": 16,
		"zone": 1,
		"username": "email@bla.com",
		"password": "pass",
		"useFanSpeed": "AUTO",
		"useSwing": false,
		"tadoMode": "MANUAL",
		"useFahrenheit": false
	}]
}
```

**Comment by iHakia** [comment]
Thanks for helping! I don't know how but I managed to work it out. 
I need one more help.
I have two tado units in my house. 
two separate zones. 
on tado api it's 
zone:1
zone:2
how can I add them both? 
can you send sample?

**Comment by nitaybz** [comment]
```
{
	"bridge": {
		"name": "Homebridge",
		"username": "CA:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},

	"description": "This is an example configuration file",

	"platforms": [],

	"accessories": [{
		"accessory": "TADO",
		"name": "Tado",
		"homeID": 18916,
		"maxValue": 31,
		"minValue": 16,
		"zone": 1,
		"username": "email@bla.com",
		"password": "pass",
		"useFanSpeed": "AUTO",
		"useSwing": false,
		"tadoMode": "MANUAL",
		"useFahrenheit": false
	},
        {
		"accessory": "TADO",
		"name": "Tado2",
		"homeID": 18916,
		"maxValue": 31,
		"minValue": 16,
		"zone": 2,
		"username": "email@bla.com",
		"password": "pass",
		"useFanSpeed": "AUTO",
		"useSwing": false,
		"tadoMode": "MANUAL",
		"useFahrenheit": false
	}]
}
```

**Comment by CrazyCreator13** [comment]
This is for Tado-AC or for the Tado Thermostat too?

**Comment by iHakia** [comment]
Thanks nitay
It really helped :+1:
