### ISSUE TITLE
Cannot read property *value* of undefined

### ISSUE THREAD

**Issue by jadomski** [nitaybz/homebridge-tado-ac-old#14]
I'm getting the following error as of an hour or so ago:

```
  Accessory [Homebridge] Getting value for Characteristic "Current Heating Cooling State" +2ms
  Accessory [Homebridge] Getting value for Characteristic "Current Temperature" +26ms
  Accessory [Homebridge] Getting value for Characteristic "Target Heating Cooling State" +11ms
  Accessory [Homebridge] Getting value for Characteristic "Temperature Display Units" +9ms
[7/19/2017, 5:07:18 PM] [Tado] The current temperature display unit is ºC
  Accessory [Homebridge] Got Characteristic "Temperature Display Units" value: 0 +3ms
  Accessory [Homebridge] Getting value for Characteristic "Target Temperature" +3ms
[7/19/2017, 5:07:19 PM] [Tado] Target temperature is unavailable
  Accessory [Homebridge] Got Characteristic "Target Temperature" value: 18 +607ms

/usr/lib/node_modules/homebridge-tado-ac/index.js:377
            if ( !obj.sensorDataPoints.insideTemperature || obj.sensorDataPoints.insideTemperature == undefined) {
                                      ^

TypeError: Cannot read property 'insideTemperature' of undefined
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-tado-ac/index.js:377:39)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

After this point, it crashes Homebridge completely and all of my other devices also go offline.

Any idea what this means? I've re-installed with no improvement.

**Comment by dansays** [comment]
Getting the same issue. API issue? I can still control my AC via the app and web.

**Comment by ghost** [comment]
Same issue. NPM TADO-AC 1.3.0

**Comment by jadomski** [comment]
The system status page at https://tado.statuspage.io says everything is operational.

Any known API changes recently?

**Comment by ghost** [comment]
Got another Error. I tried out the homebridge-tado Plugin which don't cause homebridge to crash. 

2017-7-19 13:14:32] [tado AC] The current temperature display unit is ºC
[2017-7-19 13:14:32] [tado AC] Target temperature is unavailable
/usr/local/lib/node_modules/homebridge-tado-ac/index.js:239
            if (JSON.stringify(obj.setting.power).match("OFF")) {
                                          ^

TypeError: Cannot read property 'power' of undefined
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-tado-ac/index.js:239:43)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1047:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9

**Comment by jadomski** [comment]
I've been trying to get it working and I got the same error a couple times too.

**Comment by taimurasad** [comment]
Running into same issue as everyone else here since last few hours. Any update on the fix?

**Comment by jadomski** [comment]
I'm getting different errors, here is the latest:
```
Wed, 19 Jul 2017 15:25:48 GMT Accessory [Homebridge] Getting value for Characteristic "Current Heating Cooling State"
Wed, 19 Jul 2017 15:25:48 GMT Accessory [Homebridge] Getting value for Characteristic "Current Temperature"
Wed, 19 Jul 2017 15:25:48 GMT Accessory [Homebridge] Getting value for Characteristic "Target Temperature"
Wed, 19 Jul 2017 15:25:48 GMT Accessory [Homebridge] Getting value for Characteristic "Temperature Display Units"
Wed, 19 Jul 2017 15:25:48 GMT Accessory [Homebridge] Got Characteristic "Temperature Display Units" value: 0
Wed, 19 Jul 2017 15:25:48 GMT Accessory [Homebridge] Getting value for Characteristic "Target Heating Cooling State"
/usr/lib/node_modules/homebridge-tado-ac/index.js:175
            accessory.log("Current zone mode is " + obj.setting.mode);
                                                               ^

TypeError: Cannot read property 'mode' of undefined
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-tado-ac/index.js:175:64)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```
It seems that the data coming back from the API somehow cannot be parsed by home bridge `TypeError: Cannot read property '#####' of undefined` where `#####` is the data returned by the API.

This is as far as I've looked into the issue so far. I have not yet had a chance to investigate the exact data which the API is returning yet.

**Comment by jetmcquack** [comment]
Same problem, homebridge start correctly than crashes in the moment an app poll homebridge status

**Comment by magefesa** [comment]
Same error here !  Any changes on API ??

**Comment by nitaybz** [comment]
Hey guys... my first son was just born 2 days ago... I promise you all that once I’ll leave the hospital and come home I’ll work on a fix, might’ve tomorrow.
It seems like something has changed in the api... Please be patient, it will be fixed soon

**Comment by MarcAlonso** [comment]
Thanks a lot and congratulations!

**Comment by magefesa** [comment]
No problem!!!!!! We can wait 15 days more !!! Congratulations !!! enjoy this moment!!!!! Forget this and focus on your family !!! Great !!!! 

Best regards for you and your family !!! 😃😃😃😃😃

**Comment by morilm** [comment]
Congrats Nitaybz

**Comment by jetmcquack** [comment]
take it easy nytabz!! congrats!!!!!

**Comment by jadomski** [comment]
Congrats @nitaybz!

I did some digging and enabled the logging version by running `sudo npm install -g https://github.com/nitaybz/homebridge-tado-ac#logs`

This is what is showing for me now:

`[Tado] obj = {"errors":[{"code":"unauthorized","title":"Access token expired: XXXXXXX"}]}`

In this example, `XXXXXXX` is a 906 character token from Tado.

This is as far as I've gotten at the moment, but will look into it further when I get a chance.

**Comment by nitaybz** [comment]
Guys!
Thank you all very much for your congrats.... the issue is fixed now in version 1.3.1!
even I can't leave my home inaccessible from homekit :)

**Comment by taimurasad** [comment]
Thanks! Can you tell us how to update to latest version?

Btw congrats on the new born! :)

**Comment by jadomski** [comment]
To update simply run
`sudo npm install -g homebridge-tado-ac`

**Comment by taimurasad** [comment]
shouldn't it be `sudo npm update -g homebridge-tado-ac` ?

**Comment by jadomski** [comment]
I guess you could, I've always just run the install and it simply overwrites the base files and leaves the config as is.

I don't think it matters much for a simple node project like this, but it would probably have some different behaviour with more complex projects.

**Comment by magefesa** [comment]
OK !  Let s finsih this threat with a ... **All ok with your son and wife  ????** :-)

**Comment by taimurasad** [comment]
Just used `sudo npm update -g homebridge-tado-ac` for updating and it worked fine. Everything is working great again. Thanks nitaybz!

Would love to hear the difference between the two commands `sudo npm update -g homebridge-tado-ac` vs `sudo npm install -g homebridge-tado-ac` from nitaybz!

**Comment by ronnieliew** [comment]
@nitaybz How are you getting the updated subdomain of the API server (re: 04fefc1)? Are you just intercepting the traffic from your Tado to their server?

Also congrats to you and your family!

**Comment by alexsalex** [comment]
Thank you so much! )
Congrats to you and your family!
But what was wrong?

**Comment by nitaybz** [comment]
Thank you all again!
my wife and son are doing great... I guess it's difficult like any new born baby (especially the first one). but we are managing... I really appreciate your wishes and caring.

@taimurasad regarding your question about the difference between update and install, @iJaffa was very correct with his answer... both commands are very similar, one have more advantages over the other (for both) but on homebridge plugins I guess it's not really matter. I'm using `npm install -g` **always** as it does exactly what we need by updating the package.
you can read more about it here: [npm-install-vs-update](https://stackoverflow.com/questions/12478679/npm-install-vs-update-whats-the-difference)

@ronnieliew @alexsalex - Every time there is an error in the plugin I'm using Chrome dev-tool to record the http calls to their servers using the [Tado Web App](https://my.tado.com/webapp).
most of the time, when the plugin is not working is due to small change in their call to get the token. so I'm just looking for the difference between whats in my code to the calls I recorded.
here is an example for a call, you can see here that the host is different than before:
![image](https://user-images.githubusercontent.com/16838394/28436924-696f4fbc-6da1-11e7-89ef-3d4aab89ece4.png)

**Comment by ronnieliew** [comment]
And for those who are using homebrew to install your node.js, you shouldn't be using `sudo` in your commands. 

E.g. 

`npm update -g homebridge-tado-ac` (correct)
`sudo npm update -g homebridge-tado-ac` (wrong) 


Refer to: https://docs.npmjs.com/getting-started/fixing-npm-permissions#option-3-use-a-package-manager-that-takes-care-of-this-for-you

**Comment by matthieulrg** [comment]
Hi everyone,

After updating to 1.3.2 I get the same issue. Maybe a new update in the API (again ?!). Anyone with the same issue ?

Thanks for your help and congrats @nitaybz for the baby !

Here's the log : 

> [2017-9-4 11:36:18] [Clim cuisine] The current temperature display unit is ºC
> [2017-9-4 11:36:18] [Clim salon] The current temperature display unit is ºC
> /usr/local/lib/node_modules/homebridge-tado-ac/index.js:389
>             if ( !obj.sensorDataPoints.insideTemperature || obj.sensorDataPoints.insideTemperature == undefined) {
>                                       ^
> 
> TypeError: Cannot read property 'insideTemperature' of undefined
>     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-tado-ac/index.js:389:39)
>     at emitNone (events.js:91:20)
>     at IncomingMessage.emit (events.js:185:7)
>     at endReadableNT (_stream_readable.js:974:12)
>     at _combinedTickCallback (internal/process/next_tick.js:80:11)
>     at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by nitaybz** [comment]
is it always happening? or every once in a while? when is it happening?
my plugin works perfectly so I don't think it's a change in their api

**Comment by matthieulrg** [comment]
Hi,

Yes, it’s always happening, every time I open the HomeKit app…

**Comment by nitaybz** [comment]
can you login to your tado app? what is the state of the device from there?

**Comment by matthieulrg** [comment]
Yes I can, without any issue. Both are off and I can read the temperature

**Comment by nitaybz** [comment]
please install the logs version and show me all output related:
`sudo npm install -g https://github.com/nitaybz/homebridge-tado-ac#logs`

**Comment by matthieulrg** [comment]
> [2017-9-4 13:04:11] [Clim cuisine] The current temperature display unit is ºC
> [2017-9-4 13:04:11] [Clim salon] The current temperature display unit is ºC
> [2017-9-4 13:04:12] [Clim salon] obj = {"errors":[{"code":"notFound","title":"zone with ID 1 not found"}]}
> [2017-9-4 13:04:12] [Clim salon] Target temperature is unavailable
> [2017-9-4 13:04:12] [Clim salon] obj = {"errors":[{"code":"notFound","title":"zone with ID 1 not found"}]}
> /usr/local/lib/node_modules/homebridge-tado-ac/index.js:176
>             accessory.log("Current zone mode is " + obj.setting.mode);
>                                                                ^
> 
> TypeError: Cannot read property 'mode' of undefined
>     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-tado-ac/index.js:176:64)
>     at emitNone (events.js:91:20)
>     at IncomingMessage.emit (events.js:185:7)
>     at endReadableNT (_stream_readable.js:974:12)
>     at _combinedTickCallback (internal/process/next_tick.js:80:11)
>     at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by nitaybz** [comment]
that's weird... zone is not found... do you have more logs to show?
can you show me your config?

**Comment by matthieulrg** [comment]
I think I understand. A few days ago I switch to « thermostatic mode » on Tado app which means that the app forced me to restart the config of the Tado zone 1 which is called « Salon ». But I renamed it with the same name so why there is still a bug ?

Here's the config : 

>      "accessory": "TADO",
>     	"name": "Clim salon",
>     	"homeID": xx,
>     	"maxValue": 30,
>     	"minValue": 16,
>     	"zone": 1,
>     	"username": "xx@icloud.com",
>     	"password": "xx",
>     	"useFanSpeed": "LOW",
>     	"useSwing": "ON",
>     	"tadoMode": "TADO_MODE",
>     	"useFahrenheit": false
> },    {
>     	"accessory": "TADO",
>     	"name": "Clim cuisine",
>     	"homeID": xx,
>     	"maxValue": 30,
>     	"minValue": 16,
>     	"zone": 2,
>     	"username": "xx@icloud.com",
>     	"password": "xx",
>     	"useFanSpeed": "LOW",
>     	"useSwing": "ON",
>     	"tadoMode": "TADO_MODE",
>     	"useFahrenheit": false

**Comment by matthieulrg** [comment]
Ok so I don't know why, but by renaming the zones without number 1, it works. I set a zone to "zone 2" and the other one to "zone 3" in the config file. Weird but it's working.

Thanks for your help !

**Comment by nitaybz** [comment]
maybe they changed the zones name instead of numbers... so now your config is this?
```
"accessory": "TADO",
"name": "Clim cuisine",
"homeID": xx,
"maxValue": 30,
"minValue": 16,
"zone": "zone 2",
"username": "xx@icloud.com",
"password": "xx",
"useFanSpeed": "LOW",
"useSwing": "ON",
"tadoMode": "TADO_MODE",
"useFahrenheit": false
```

**Comment by nitaybz** [comment]
and how did you change to thermostatic mode in Tado app... I don't see this option in my app

**Comment by matthieulrg** [comment]
Yup, juste like this : 

> "accessory": "TADO",
> "name": "Clim salon",
> "homeID": xx,
> "maxValue": 30,
> "minValue": 16,
> "zone": "zone 2",
> "username": "xx@icloud.com",
> "password": "xx",
> "useFanSpeed": "LOW",
> "useSwing": "ON",
> "tadoMode": "TADO_MODE",
> "useFahrenheit": false
> 
> 
> "accessory": "TADO",
> "name": "Clim cuisine",
> "homeID": xx,
> "maxValue": 30,
> "minValue": 16,
> "zone": "zone 3",
> "username": "xx@icloud.com",
> "password": "xx",
> "useFanSpeed": "LOW",
> "useSwing": "ON",
> "tadoMode": "TADO_MODE",
> "useFahrenheit": false

**Comment by nitaybz** [comment]
oh yes I saw!
what is it do?

UPDATE: never mind... I just read about it!, cool feature.

**Comment by matthieulrg** [comment]
Honestly, don't activate it. 
The idea is good : all the control are set by the Tado to the unit. You just ask Tado for the perfect temperature and it will adjust all the settings on your AC depending on what the Tado sensors are receiving. Most of the AC are bad with temperature, you ask for 22° and after some hours it's 24° because the unit didn't stop heating... With this mode, Tado will correct this.

BUT
If you use this mode you loose Dry Mode and Fan Mode. Plus, you're forced to restart all the config with the teaching mode (soooo long). Finally to go back in "Non thermostatic mode" you have to call the support... Also, you may have a lot of "beep" because the Tado is constantly sending new commands to adjust the temperature.

If you try, tell me what do you think about it !

**Comment by nitaybz** [comment]
hey Guys!
New version is available to download... v 2.0
this version require a whole new config, please read [README.md](https://github.com/nitaybz/homebridge-tado-ac/blob/master/README.md) file before installing.
`sudo npm install -g homebridge-tado-ac`

This version will give you much more control on your AC device including Fan mode, swing & rotation speed control.

I would love to get your feedback on that!

Please submit new issues (or feedback) to the [New Git](https://github.com/nitaybz/homebridge-tado-ac/issues) which has the same name but it's completely new. the [Old Git](https://github.com/nitaybz/homebridge-tado-ac-old) will not be supported anymore

Thanks a lot!
