### ISSUE TITLE
homebridge not working again

### ISSUE THREAD

**Issue by magefesa** [nitaybz/homebridge-tado-ac-old#17]
Hi ! Congratulations again for your recen tpaternity ! 
My homebridge is not crashing, but TADO is not available again... any ideas please ? It has been working since last update perfectly...

Thanks !

**Comment by magefesa** [comment]
I answer myself ! !
The problem was between TADO APP and HOMEKIT ! Stop manual operation on TADO app and try again on HOME !! It will workS ! ! ! !

**Comment by nitaybz** [comment]
Glad you solved it... Thanks for the wishes :)
Closing...
