### ISSUE TITLE
How is the Tado AC Control displayed in the Home app?

### ISSUE THREAD

**Issue by jojost1** [nitaybz/homebridge-tado-ac-old#3]
Hi, see title. Curious and can't find it anywhere. Could someone post some screenshots? Thanks :)

**Comment by nitaybz** [comment]
it looks like any homekit thermostat: 
http://media.idownloadblog.com/wp-content/uploads/2016/06/ios-10-new-home-app.jpg
http://thewirecutter.com/wp-content/uploads/2016/11/smart-thermostat-ecobee3-lite-ios-screenshots-lowres-.jpg

**Comment by jojost1** [comment]
So when I have a thermostat and an AC controlled by Tado AC Control & homebridge, I have two thermostats in the room I have to both set at the same temperature pretty much to work together? Thanks.

**Comment by nitaybz** [comment]
That really depends on your devices.... each of them will be individual, the Tado AC control will not automatically turn off/on your AC when a certain temperature is reached (As far as I know).

So you can choose which device to use, but with homekit you can have them both without any interruption to each other.

**Comment by jojost1** [comment]
Thanks!
