### ISSUE TITLE
Not turns on the AC

### ISSUE THREAD

**Issue by ghost** [nitaybz/homebridge-tado-ac-old#4]
After setting this up, finding my HomeID (from an other api: https://my.tado.com/mobile/1.9/...) it's not controlling the AC.

Any ideas on this?

Config:
```
                "accessory": "TADO",
                "name": "Tado",
                "homeID": 66341,
                "maxValue": 28,
                "minValue": 18,
                "zone": 1,
                "username": "EMAIL",
                "password": "PW",
                "useFanSpeed": "AUTO",
                "useSwing": false,
                "tadoMode": "MANUAL",
                "useFahrenheit": false
```

HomeBridge result:

[5/30/2017, 12:23:35 PM] Homebridge is running on port 51822.
[5/30/2017, 12:24:12 PM] [Tado] The current temperature display unit is ºC
[5/30/2017, 12:24:13 PM] [Tado] Room temperature is 24.53ºC
[5/30/2017, 12:24:13 PM] [Tado] Current zone mode is undefined
[5/30/2017, 12:24:13 PM] [Tado] Current power state is OFF
[5/30/2017, 12:24:13 PM] [Tado] Current operating state is OFF
[5/30/2017, 12:24:13 PM] [Tado] Target temperature is unavailable
[5/30/2017, 12:24:13 PM] [Tado] Target operating state is OFF
[5/30/2017, 12:24:25 PM] [Tado] Force cooling
[5/30/2017, 12:24:25 PM] [Tado] Set target temperature to 22º

**Comment by nitaybz** [comment]
make sure that you config match the AC settings in Tado app, for example, if you have the option to change the swing of the AC you HAVE to set a value in the config, or if you can't control the Fan speed in Tado app or if you don't have the option for auto speed, then, you are not allowed to use those values.

**Comment by nitaybz** [comment]
not sure the json file suppose to be that big, feel free to send your credentials to nitaybz@gmail.com
and let me know when is a good time to turn your ac on and off occasionally for testing.... you can also contact me on homebridge slack group if you're using that.

**Comment by alexsalex** [comment]
The same issue. I can turn off AC, but I can't turn on. From tado app I can do it without a problem.

**Comment by nitaybz** [comment]
did you read my last message? does your config match your tado app settings?
please show your config.

**Comment by alexsalex** [comment]
"accessories": [
	{
	  "accessory": "TADO",
	  "name": "Tado",
	  "homeID": 54321,
	  "maxValue": 89,
	  "minValue": 64,
	  "zone": 1,
	  "username": "login",
	  "password": "psw",
	  "useFanSpeed": "AUTO",
	  "tadoMode": "MANUAL",
	  "useFahrenheit": true
	}
    ],


I chnge useFahrenheit to false, and temperature shows normal, but when I try to change temp it is the same 192 degree.

**Comment by nitaybz** [comment]
you can use this link to show your capabilities on tado app:
https://my.tado.com/api/v2/homes/54321/zones/1/capabilities?username=usr&password=mypassword
please change everything in the <> according to your account.

you can only use the options you see... please show me what you get

**Comment by alexsalex** [comment]
{"errors":[{"code":"accessDenied","title":"current user is not allowed to access this resource"}]}

**Comment by nitaybz** [comment]
please try again, change homeID username and password, i changed the link

**Comment by alexsalex** [comment]
sorry(

{"type":"AIR_CONDITIONING","COOL":{"temperatures":{"celsius":{"min":18,"max":32,"step":1.0},"fahrenheit":{"min":64,"max":89,"step":1.0}},"fanSpeeds":["AUTO","HIGH","MIDDLE","LOW"]},"DRY":{},"FAN":{"fanSpeeds":["HIGH","MIDDLE","LOW"]},"HEAT":{"temperatures":{"celsius":{"min":15,"max":27,"step":1.0},"fahrenheit":{"min":59,"max":81,"step":1.0}}}}

**Comment by nitaybz** [comment]
seems like your capabilities are not consistent between COOL and HEAT, why don't you have fanSpeeds on the HEAT option? and is it really having different minimum and maximum temperatures on different modes? (COOL & HEAT)

**Comment by alexsalex** [comment]
this questions is better to ask for air cond manufacture))) I don't know, it is AC like this one... what you recommend me? is this related to funny numbers? why in old version of plugin everything is ok?

After I change useFahrenheit to false, I can't turn on AC, but I can turn off it.

**Comment by nitaybz** [comment]
I'll try my best to help you solve it...
by those setting it seems like you should be able control the COOL mode.
but lets start with your other issue, did you managed to fix the temperature issue that I wrote you about?

**Comment by alexsalex** [comment]
I'm sorry, it's deep night here. Where you wrote about solution?
In logs seems like everithing is ok... just shows in Home app really weird...

[2017-6-27 01:35:33] [Tado] The current temperature display unit is ºF
[2017-6-27 01:35:34] [Tado] Target operating state is OFF
[2017-6-27 01:35:34] [Tado] Current zone mode is undefined
[2017-6-27 01:35:34] [Tado] Current power state is OFF
[2017-6-27 01:35:34] [Tado] Current operating state is OFF
[2017-6-27 01:35:34] [Tado] Target temperature is unavailable
[2017-6-27 01:35:34] [Tado] Room temperature is 85.59ºF
[2017-6-27 01:35:39] [Tado] Set target temperature to 89º
[2017-6-27 01:35:41] [Tado] Force cooling
[2017-6-27 01:35:41] [Tado] Set target temperature to 89º
[2017-6-27 01:35:47] [Tado] Set target state to off

**Comment by nitaybz** [comment]
so you still have the funny numbers in the home app?
so for example when you set in the app 192 you see in the logs 89 degrees?

**Comment by alexsalex** [comment]
correct)

![2017-06-27 01-50-47 3822](https://user-images.githubusercontent.com/17325366/27579237-bb64b114-5adb-11e7-95fe-bc055ad6aa0d.png)

**Comment by nitaybz** [comment]
try to install from here:
`sudo npm install -g https://github.com/nitaybz/homebridge-tado-ac`

**Comment by alexsalex** [comment]
much better))) but:
![2017-06-27 02-04-01 3823](https://user-images.githubusercontent.com/17325366/27579639-14c92d10-5add-11e7-9053-2a34ed2070e6.png)
Like I said before, in old plugin everything is ok. I want to help you)

**Comment by nitaybz** [comment]
please try again and install from the same command

**Comment by nitaybz** [comment]
my latest update should fix this issue:
`sudo npm install -g homebridge-tado-ac`

**Comment by matthieudu06** [comment]
Hi everyone,

I have exactly the same problem. I can turn off the tado but nothing more. When I change the setting in HomeKit, it appear just like the command is correctly setup (when I choose cool mode, the icon in HomeKit is set to cool mode) and just after a few seconds it return to the "off" icon (he's original state).

The settings are the same in the tado app and I'm running the last version of tado-ac.

Config :

>   
  	"accessory": "TADO",
    	"name": "Clim salon",
    	"homeID": 75604,
    	"maxValue": 30,
    	"minValue": 16,
    	"zone": 1,
    	"username": "nm.trash@icloud.com",
    	"password": "ZV4m^h6h$g36",
    	"useFanSpeed": "LOW",
    	"useSwing": true,
    	"tadoMode": "TADO_MODE",
    	"useFahrenheit": false
